default_stages: [manual]

repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 spacy_llm
        language: system
        types: [python]
        require_serial: true
        verbose: true
      - id: black
        name: black
        entry: black --check --diff spacy_llm
        language: system
        types: [python]
        require_serial: true
      - id: pyright
        name: pyright
        entry: pyright spacy_llm
        language: system
        types: [python]
        require_serial: true
        verbose: true
