repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      entry: black spacy_llm
      language_version: python3.7
      additional_dependencies: ['click==8.0.4']
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.259'
    hooks:
    - id: ruff